#include "Map.h"

// ========================================
// CONSTRUCTOR
// ========================================

Map::Map() {

    grid = {

    {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,FLOOR,WALL,WALL,WALL,FLOOR,FLOOR,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
    };
}

// ========================================
// GET TILE
// ========================================

TileType Map::getTile(int x, int y) {

    if (
        x < 0 ||
        y < 0 ||
        y >= grid.size() ||
        x >= grid[0].size()
    ) {
        return WALL;
    }

    return grid[y][x];
}

// ========================================
// SET TILE
// ========================================

void Map::setTile(
    int x,
    int y,
    TileType tile
) {

    if (
        x < 0 ||
        y < 0 ||
        y >= grid.size() ||
        x >= grid[0].size()
    ) {
        return;
    }

    grid[y][x] = tile;
}

// ========================================
// WIDTH
// ========================================

int Map::getWidth() {

    return grid[0].size();
}

// ========================================
// HEIGHT
// ========================================

int Map::getHeight() {

    return grid.size();
}