#include "Map.h"

Map::Map() {

    grid = {

    {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,FLOOR,WALL,WALL,WALL,FLOOR,FLOOR,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL},

    {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
    };
}