#include "Map.h"

Map::Map() {
    grid = {

    {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},

    {WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,COIN,EMPTY,EMPTY,WALL},

    {WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,EMPTY,EMPTY,WALL,WALL,WALL,EMPTY,EMPTY,WALL,WALL,EMPTY,WALL},

    {WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,KEY,WALL},

    {WALL,EMPTY,WALL,WALL,WALL,WALL,WALL,EMPTY,WALL,EMPTY,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,EMPTY,WALL},

    {WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,WALL},

    {WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,WALL,EMPTY,WALL,WALL,EMPTY,WALL},

    {WALL,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,WALL},

    {WALL,EMPTY,WALL,EMPTY,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,WALL},

    {WALL,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,WALL},

    {WALL,EMPTY,WALL,WALL,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,WALL,EMPTY,WALL},

    {WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,WALL},

    {WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL},

    {WALL,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,DOOR,WALL},

    {WALL,EMPTY,WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,EMPTY,WALL},

    {WALL,EMPTY,WALL,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,WALL},

    {WALL,EMPTY,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,WALL,WALL,WALL,WALL,EMPTY,WALL,WALL,EMPTY,WALL},

    {WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,ENEMY,WALL},

    {WALL,HEART,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL},

    {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL}
};
}

TileType Map::getTile(int x, int y) {
    return grid[y][x];
}

int Map::getWidth() {
    return grid[0].size();
}

int Map::getHeight() {
    return grid.size();
}